### ISSUE TITLE
Few icons not colorised by color_theme.py

### ISSUE THREAD

**Issue by Muqtxdir** [fkohlgrueber/yaru-anycolor#2]
color_theme.py script does not modify colors to icons present under:

-**yaru/icons/src/fullcolor/legacy/document-open.svg**
-**yaru/icons/src/fullcolor/legacy/document-export.svg**
-**yaru/icons/src/fullcolor/emblems/emblem-symbolic-link.svg**

Thankyou

**Comment by fkohlgrueber** [comment]
That's right! Where are the document-open and document-export icons shown?

**Comment by Muqtxdir** [comment]
Well, I use Transmission for .torrent files so the open menu uses it
![Screenshot from 2020-05-22 12-01-16](https://user-images.githubusercontent.com/54065734/82638372-67a76200-9c24-11ea-9b37-323eb5a84ca9.png)

**Comment by fkohlgrueber** [comment]
I can't reproduce what you've shown. When installing transmission (`apt install transmission`), it shows a legacy folder icon instead of the one you showed. Screenshot:
![Screenshot from 2020-05-22 09-15-44](https://user-images.githubusercontent.com/9519668/82641747-28b9e200-9c0d-11ea-9524-d5aced269a05.png)

Did you modify anything else?

**Comment by Muqtxdir** [comment]
Thanks for looking into this specifically

Yes, even yaru theme shows the same legacy icon but for some reason the colored-yaru theme displays that icon (This is embarrassing!)

I do not know whether this might be the difference but I did not modify anything except during theme installation instead of doing `meson build -D gnome-shell-gresource=true` I did `meson build`

**Comment by fkohlgrueber** [comment]
I just checked, standard Yaru also displays the icons shown in the screenshot I posted. I don't know why your setup shows another icon for yaru-anycolor. What's your OS version? Ubuntu 20.04?

**Comment by Muqtxdir** [comment]
I use Ubuntu 20.04 but I use the theme from yaru-master branch
Is it because of `meson build` (I'm new to theming)?

But I guess, adding these .svg's to yaru-anycolor `color_theme.py` wouldn't break anything
Thanks

**Comment by Muqtxdir** [comment]
Hi, I build the theme again, It is now using the correct old-legacy icon in Transmission
![Screenshot from 2020-05-22 13-59-17](https://user-images.githubusercontent.com/54065734/82647890-785fd400-9c34-11ea-99c6-cf1a3284849f.png)

Sorry for the trouble
Thanks for helping!

**Comment by fkohlgrueber** [comment]
Ok. I wouldn't bother trying to change those legacy icons. Anyway, I've just pushed an update that changes the color of `emblem-symbolic-link`.


![screenshot](https://user-images.githubusercontent.com/9519668/82649143-0cbc3d80-9c19-11ea-826d-cf366b96e6ad.png)

Can this issue be closed?

**Comment by Muqtxdir** [comment]
Thanks
Yes,close this issue
