### ISSUE TITLE
Color not changed for toggle-on in dark theme(gnome-shell)

### ISSUE THREAD

**Issue by Muqtxdir** [fkohlgrueber/yaru-anycolor#3]
Hi,
The "Dark" shell theme still uses the standard Yaru based colors for toggle-on.svg for do-not disturb toggle in Notification area
The **toggle-on-dark.svg** in gnome-shell is not colored by `color_theme.py`

![1](https://user-images.githubusercontent.com/54065734/83171210-651c9f00-a133-11ea-87a7-77f6ac089023.jpg)

The toggles screenshot:

![Screenshot from 2020-05-28 22-39-09](https://user-images.githubusercontent.com/54065734/83171685-1d4a4780-a134-11ea-85fb-a5f8fb952490.png)

Thanks!

**Comment by fkohlgrueber** [comment]
Hi, thanks for reporting! I just pushed a fix for this. I'll close this issue, but feel free to comment below if the fix doesn't work for you.

**Comment by Muqtxdir** [comment]
It works

Thanks!
